name: gest_agent
description: "Application simple pour agent Wave"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Backend
  pocketbase: ^0.23.0+1
  
  # Local Storage
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  
  # Notifications
  flutter_local_notifications: ^17.1.2
  
  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  glados: ^1.0.0

flutter:
  uses-material-design: true
